const UPDATE = 'app/editor/UPDATE'
const REQUEST_VALIDATE = 'app/editor/REQUEST_VALIDATE'
const SUCCESS_VALIDATE = 'app/editor/SUCCESS_VALIDATE'
const FAILURE_VALIDATE = 'app/editor/VALIDATE_FAILURE'

export { UPDATE, REQUEST_VALIDATE, SUCCESS_VALIDATE, FAILURE_VALIDATE }
